# File to store secret info - Twitter API keys, etc.
twitter:
  consumer_key: "my_twitter_consumer_key"
  consumer_secret: "my_twitter_consumer_secret"
  oauth_key: "my_twitter_oauth_key"
  oauth_secret: "my_twitter_oauth_secret"
# If specified, log_file is the filename for a log of all
# ship positions and any comings/goings
#log_file: "movements.log"
# If true, verbose causes lots more detail to be output
# to stdout
verbose: false
